services:
  app:
    build: .
    container_name: minecraft-server-controller
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    ports:
      - 8080:80

  server:
    image: nano-minecraft-server:26.2
    environment:
      - MEMORY_MIN=2G
      - MEMORY_MAX=10G
    ports:
      - 25565:25565
      - 8123:8123