services:
  app:
    #user: "0:0"
    build: .
    container_name: minecraft-server-controller
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    ports:
      - 8080:80
    volumes:
      - type: volume
        source: mc-data
        target: /data
        volume:
          nocopy: true
      - ./backup:/backup

  server:
    image: nano-minecraft-server:26.2
    environment:
      - MEMORY_MIN=2G
      - MEMORY_MAX=10G
    ports:
      - 25565:25565
      - 8123:8123
    volumes:
      - mc-data:/data
volumes:
  mc-data: